export const MOCK_VULNERABILITY_CATALOG = [
  {
    name: "SQL Injection",
    desc: "Unsanitized user input in parameterized queries allow database manipulation.",
    severity: "Critical",
    tone: "red",
    cwe: "CWE-89",
    path: "/api/v1/auth/login",
    impact: "Attackers may read, alter, or delete database records and bypass authentication.",
    fix: "Use parameterized queries, execute validation checklists, and enforce security controls.",
  },
  {
    name: "Cross Site Scripting (XSS)",
    desc: "Reflected input payload executes scripts in users web browser context.",
    severity: "High",
    tone: "orange",
    cwe: "CWE-79",
    path: "/search?query=",
    impact: "Malicious scripts may steal session cookies or hijack client layout flows.",
    fix: "Escape and sanitize outputs dynamically, enforce strict Content Security Policies (CSP).",
  },
  {
    name: "Security Misconfiguration",
    desc: "Server exposes directory index listings and debugging headers publicly.",
    severity: "Medium",
    tone: "yellow",
    cwe: "CWE-200",
    path: "/assets/",
    impact: "Attackers find system layouts and private code files exposing metadata leaks.",
    fix: "Disable directory index views in server configuration files and strip debug headers.",
  },
  {
    name: "Sensitive Data Exposure",
    desc: "API payloads expose credential keys or user detail metrics without tokens.",
    severity: "High",
    tone: "orange",
    cwe: "CWE-532",
    path: "/api/v1/users/profile",
    impact: "Unauthorized access to user profile metadata values.",
    fix: "Filter model outputs in controllers and restrict public exposure endpoints.",
  },
  {
    name: "Insecure Direct Object Reference (IDOR)",
    desc: "User parameters index record records directly without authorization checks.",
    severity: "Medium",
    tone: "yellow",
    cwe: "CWE-639",
    path: "/api/v1/billing/invoice?id=",
    impact: "Users read or download invoices belonging to other tenants.",
    fix: "Enforce document object-level permissions check on controller hooks.",
  },
  {
    name: "Missing Security Headers",
    desc: "HTTP responses lack HSTS, X-Frame-Options or Content-Type-Options configs.",
    severity: "Low",
    tone: "green",
    cwe: "CWE-693",
    path: "/",
    impact: "Browser has fewer built-in guards against clickjacking and type-sniffing exploits.",
    fix: "Set Helmet configs or load custom secure headers middleware.",
  },
];

export const INITIAL_VULNERABILITIES = [
  {
    name: "SQL Injection",
    domain: "example.com",
    severity: "High",
    status: "Open",
    detectedAt: "16 May 2024, 10:30 AM",
    tone: "orange",
  },
  {
    name: "Cross Site Scripting (XSS)",
    domain: "testsite.com",
    severity: "Critical",
    status: "Open",
    detectedAt: "16 May 2024, 09:15 AM",
    tone: "red",
  },
  {
    name: "Security Misconfiguration",
    domain: "myapp.io",
    severity: "Medium",
    status: "Open",
    detectedAt: "16 May 2024, 08:45 AM",
    tone: "yellow",
  },
  {
    name: "Sensitive Data Exposure",
    domain: "demo.org",
    severity: "High",
    status: "Open",
    detectedAt: "16 May 2024, 07:20 AM",
    tone: "orange",
  },
  {
    name: "Cross Origin Resource Sharing",
    domain: "vulnerable.net",
    severity: "Low",
    status: "Open",
    detectedAt: "16 May 2024, 06:10 AM",
    tone: "green",
  },
];
