steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'VITE_API_BASE_URL=https://breach-radar-backend-539618567961.europe-west1.run.app/api/v1',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:$COMMIT_SHA',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:latest',
      '-f', 'Dockerfile',
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:latest']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'breach-radar-frontend',
      '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/breach-radar/breach-radar-frontend:latest'
